name: Build Android App Bundle (AAB)

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Signed AAB
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Decode Keystore
      env:
        ENCODED_STRING: ${{ secrets.KEYSTORE_BASE64 }}
      run: |
        echo $ENCODED_STRING | base64 -di > code/app/keystore.jks
    - name: Make gradlew executable
      run: chmod +x code/gradlew
    - name: Build Release AAB
      working-directory: ./code
      env:
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      run: ./gradlew bundleRelease
    - name: Upload AAB
      uses: actions/upload-artifact@v4
      with:
        name: app-release.aab
        path: code/app/build/outputs/bundle/release/app-release.aab
    - name: Clean up keystore
      if: always()
      run: rm -f code/app/keystore.jks
